site_name: Lurch Deductive Engine Documentation
nav:
- Home: index.md
dev_addr: 127.0.0.1:8888
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.tasklist
